stages:
  data_ingestion:
    cmd: python insurance_src/components/data_ingestion.py
    deps:
      - insurance_src/components/data_ingestion.py
      - insurance_src/entity/config_entity.py
      - insurance_src/entity/artifact_entity.py
    outs:
      - artifact/data_ingestion/feature_store/raw.csv
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv


  data_validation:
    cmd: python insurance_src/components/data_validation.py
    deps:
      - insurance_src/components/data_validation.py
      - insurance_src/entity/artifact_entity.py
      - insurance_src/entity/config_entity.py
      - artifact/data_ingestion/ingested/train.csv
      - artifact/data_ingestion/ingested/test.csv
    outs:
      - artifact/data_validation/drift_report/dataset_drift.yaml
      - artifact/data_validation/drift_report/probability_drift_target_column.yaml
      - artifact/data_validation/validated/train.csv
      - artifact/data_validation/validated/test.csv
      - artifact/data_validation/validation.yaml


  data_transformation:
    cmd: python insurance_src/components/data_transformation.py
    deps:
      - insurance_src/components/data_transformation.py
      - insurance_src/entity/config_entity.py
      - insurance_src/entity/artifact_entity.py
      - artifact/data_validation/drift_report/dataset_drift.yaml
      - artifact/data_validation/drift_report/probability_drift_target_column.yaml
      - artifact/data_validation/validated/train.csv
      - artifact/data_validation/validated/test.csv
      - artifact/data_validation/validation.yaml
    outs:
      - artifact/data_transformation/transformed_numpy_array/train.npy
      - artifact/data_transformation/transformed_numpy_array/test.npy
      - artifact/data_transformation/transformed_binary_object/preprocessing.pkl


  model_trainer:
    cmd: python insurance_src/components/model_trainer.py
    deps:
      - insurance_src/components/model_trainer.py
      - insurance_src/entity/config_entity.py
      - insurance_src/entity/artifact_entity.py
      - artifact/data_transformation/transformed_numpy_array/train.npy
      - artifact/data_transformation/transformed_numpy_array/test.npy
      - artifact/data_transformation/transformed_binary_object/preprocessing.pkl

    outs:
      - artifact/model_trainer/trained_model/model.pkl
      - artifact/model_trainer/trained_model/metrics.yaml


  
  model_evaluation:
    cmd: python insurance_src/components/model_evaluation.py
    deps:
      - insurance_src/components/model_evaluation.py
      - insurance_src/entity/config_entity.py
      - insurance_src/entity/artifact_entity.py
      - artifact/model_trainer/trained_model/model.pkl
      - artifact/model_trainer/trained_model/metrics.yaml
      
    outs:
      - artifact/model_evaluation/model_evaluation_artifact.yaml


  model_pusher:
    cmd: python insurance_src/components/model_pusher.py
    deps:
      - insurance_src/components/model_pusher.py
      - insurance_src/cloud_storage/aws_storage.py
      - insurance_src/entity/artifact_entity.py
      - insurance_src/entity/config_entity.py
      - artifact/model_evaluation/model_evaluation_artifact.yaml
      - insurance_src/entity/s3_estimator.py
      - artifact/model_trainer/trained_model/model.pkl
    # outs:
    #   - s3://your-bucket-name/path/to/model/  # This is logical; DVC doesn't track S3 objects but you document that your model is pushed here.