
[project]
name = "src"
version = "0.0.1"
description = "Insurance Fraud Detection project"
authors = [
    { name = "Mahesh Pachpande", email = "pachpandemahesh300@gmail.com" }
]

[tool.setuptools]
packages = {find = {}}

[tool.setuptools.dynamic]
dependencies = {file = "requirements.txt"}